### ISSUE TITLE
 hwloc_gl_query_display_ and hwloc_gl_get_gpu_display are buggy

### ISSUE THREAD

**Issue by hernando** [BlueBrain/hwloc#4]
hwloc_gl_query_display_ call XCloseDisplay and it will be closed again on return.
hwloc_gl_get_gpu_display must call XCloseDisplay before returning inside the inner loop.

Fixing these bugs causes the slow intiailization problem to reappear in the vizcluster.

**Comment by eile** [comment]
Ok, doing an upstream merge now and will try to resolve this in the process.
